spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: postgres
    password: KXumora1220
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never